update tutorial_print.py
CAIDA/pybgpstream pull request #44
Opened 2021-04-12 04:01 UTC by chenrui333

1. add collectors
2. remove dup elem.type

2021-04-12 12:02 UTC, digizeph approved these changes

2021-04-15 12:18 UTC, digizeph requested changes
After further review, I think we can change the filter string and field from `collector` to `collectors`, but no need to make other changes.

2021-04-15 12:18 UTC, digizeph commented on examples/tutorial_print.py
>      filter='collector rrc06 and type updates',
Sorry, I missed it in the first review. We already have a filter for collector as part of the filter string here. 
The added `collectors` is not necessary.

2021-04-15 12:18 UTC, digizeph commented on examples/tutorial_print.py
>  #      collector="rrc06",
also we have `collector` filter set here too (though it's for single collector).

2021-04-15 14:02 UTC, chenrui333 commented on examples/tutorial_print.py
>      filter='collector rrc06 and type updates',
yeah, I will just remove the single collector then. Somehow I feel like this is more collector issue rather than the syntax issue.

2021-04-15 14:05 UTC, digizeph commented on examples/tutorial_print.py
> +    collectors=["route-views.sg", "route-views.eqix"],
this needs to be in the filter string. the point of this block is to show how the filter string works in pybgpstream. 
https://github.com/CAIDA/libbgpstream/blob/master/FILTERING

2021-05-14 16:15 UTC, closed without merging